Repository Ramaz-Upper-School/RamLife, pull requests merged in 2021-04, with the labels that each got.

#53 Add two GitHub actions
  .github/workflows/analyze.yml
  .github/workflows/documentation.yml
Labels: Code health, Critical

#44 Credits Page UI
  lib/app.dart
  lib/data.dart
  lib/pages.dart
  lib/src/data/contributor.dart
  lib/src/pages/credits.dart
  lib/src/pages/drawer.dart
  pubspec.lock
Labels: New feature

#68 Fixed Ios issue
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  pubspec.lock
  pubspec.yaml
Labels: meta

#66 Migrated from ModelListener widget to ModelListener extends State
  lib/src/models/view/calendar_editor.dart
  lib/src/models/view/home.dart
  lib/src/pages/admin/calendar.dart
  lib/src/pages/admin/schedules.dart
  lib/src/pages/builders/day_builder.dart
  lib/src/pages/builders/reminder_builder.dart
  lib/src/pages/builders/sports_builder.dart
  lib/src/pages/dashboard.dart
  lib/src/pages/feedback.dart
  lib/src/pages/home.dart
  lib/src/pages/reminders.dart
  lib/src/pages/schedule.dart
  lib/src/pages/sports.dart
  lib/src/widgets/generic/class_list.dart
  lib/src/widgets/generic/footer.dart
  lib/src/widgets/generic/model_listener.dart
  lib/src/widgets/responsive_scaffold/navigation_item.dart
  lib/src/widgets/responsive_scaffold/scaffold.dart
Labels: Code health
